Web/GameProject/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GameProject.Extensions;
using GameProject.Features;
using GameProject.Service.Common.GameService;
using GameProject.Service.Common.WordService.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameProject.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService gameService;

        public GameController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Index()
        {
            var words = gameService.GetRandomWords();
            if (!words.Any())
            {
                return View("_ErrorView");
            }
            HttpContext.Session.SetObject(this.User.Identity.Name + "Word", words);
            var word = gameService.GetSecretWord(words.First());
            return View(word);
        }
        
        [HttpGet]
        public JsonResult CheckWord(string secretWord, string wordOrLetter)
        {
            var userId = User.GetUserId();
            try
            {
                //Использую сессии , что бы каждый раз не обращаться в БД
                var words = HttpContext.Session.GetObject<IEnumerable<WordModel>>(this.User.Identity.Name + "Word");
                var word = gameService.CheckWord(ref words, secretWord, wordOrLetter, userId);
                if (word == null)
                {
                    return Json(new
                    {
                        gameOver = true,
                        isWin = true
                    });
                }

                HttpContext.Session.SetObject(this.User.Identity.Name + "Word", words);

                return Json(new
                {
                    gameOver = false,
                    model = new
                    {
                        secretWord = word.SecretWord,
                        tryCount = word.TryCount,
                        question = word.Question
                    }
                });
            }
            catch (ArgumentOutOfRangeException)
            {
                return Json(new
                {
                    gameOver = true,
                    isWin = false
                });
            }
        }

        [HttpGet]
        public IActionResult Results(bool isWin)
        {
            var id = User.GetUserId();
            if (isWin)
            {
                ViewBag.Result = "Поздравляем! Вы победили!";
            }
            else
            {
                ViewBag.Result = "Печально! Вы проиграли!";
            }
            return View();
        }
    }
}

Web/GameProject/Views/Game/Index.cshtml
@model GameProject.Service.Common.WordService.Models.WordModel


<h3>Попытайтесь угадать слово по буквам. На угадывание слова целиком дается лишь одна попытка.</h3>
<br/>
<h1><span id="question">@Model.Question</span></h1>
<h2>Ответ: <span id="secretWord">@Model.SecretWord</span></h2>
<h5>Осталось попыток: <span id="tryCount">@Model.TryCount</span></h5>
<div class="row">

    <div class="col-md-4" >
        <form id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="SecretWord" type="hidden"/>
            <input asp-for="TryCount" type="hidden"/>
            <div class="form-group">
                <label class="control-label">Введите предполагаемую букву или слово целиком</label>
                <input id="letter" name="letter" class="form-control" required/>
                <span id="letterRequired" class="text-danger">Введите букву или слово</span>
            </div>
        </form>
    </div>
</div>
<div class="col-3">
    <button type="button" class="btn btn-primary " onclick="findWord()">Принять</button>
</div>

<script>
    $(document).ready(function () {
        $("#letterRequired").hide();
    });
    
    function findWord() {
        if ($("#letter").val() == "") {
            $("#letterRequired").show();
            return;
        } else {
            $("#letterRequired").hide();
        }
        $.ajax({
            type: "GET",
            url: "@Url.Action("CheckWord", "Game")",
            data: { secretWord: $("#SecretWord").val(),  wordOrLetter: $("#letter").val() },
            success: function (responce) {
                if (responce.gameOver) {
                    var link = "@Url.Action("Results","Game")";
                    link += "?isWin=" + responce.isWin;
                    window.location.href = link;
                } else {
                    prepareWord(responce.model);
                } 
            } 
        });
    }

    function prepareWord(word) {
        $("#SecretWord").val(word.secretWord);
        $("#secretWord").html(word.secretWord);
        $("#tryCount").html(word.tryCount);
        $("#question").html(word.question);
        $("#letter").val("");
    }
</script>

Web/GameProject/Views/Game/Results.cshtml
@{
    ViewData["Title"] = "Results";
}

<h1>Результат</h1>
<h3>@ViewBag.Result</h3>